  
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: curl -L https://api.nest.saker.build/bundle/download/saker.build-v$(curl -s https://mirror.nest.saker.build/badges/saker.build/latest.txt) -o saker.build.jar
  displayName: 'Download saker.build'
  
- script: java -jar saker.build.jar -bd build -trace pwd://build/build_test.trace test
  displayName: 'Test'
- task: PublishBuildArtifacts@1
  condition: always()
  displayName: 'Publish test trace'
  inputs:
    pathtoPublish: build/build_test.trace
    artifactName: test_trace

- script: java -jar saker.build.jar -bd build -trace pwd://build/build_test_direct.trace test_direct
  displayName: 'Test direct'
- task: PublishBuildArtifacts@1
  condition: always()
  displayName: 'Publish test direct trace'
  inputs:
    pathtoPublish: build/build_test_direct.trace
    artifactName: build_test_direct

- script: java -jar saker.build.jar -bd build -trace pwd://build/build_export.trace export
  displayName: 'Export'
- task: PublishBuildArtifacts@1
  condition: always()
  displayName: 'Publish export trace'
  inputs:
    pathtoPublish: build/build_export.trace
    artifactName: export_trace
