  
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    # set the -e so the bash script exists if a command fails
    set -e
    curl -s https://api.nest.saker.build/bundle/download/saker.build-v0.8.0 -o saker.build.jar
    java -jar saker.build.jar -bd build test
    java -jar saker.build.jar -bd build export
  displayName: 'Export library JAR'