  
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: curl -L https://api.nest.saker.build/bundle/download/saker.build-v$(curl -s https://mirror.nest.saker.build/badges/saker.build/latest.txt) -o saker.build.jar
  displayName: 'Download saker.build'
- script: java -jar saker.build.jar -bd build test
  displayName: 'Test'  
- script: java -jar saker.build.jar -bd build export
  displayName: 'Export'